version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/Personal-expense-Tracker
hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 600
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_service.sh
      timeout: 300
      runas: ec2-user
